### PR TITLE
food 

### PR DESCRIPTION
**Pull request by Onaysa**

### CODE REVIEW

**Comment by ismailsaoudi** [comment]
can you please change the name of the index.html to foodPage.html .
it's easier ot link them later

**Review by ismailsaoudi — CHANGES_REQUESTED** [review]
please change the index.html to foodPage.html .   thank you

**Comment by fubaru** [comment]
Currently the merge request is for the food branch changes to be merged into the main branch. Make sure it is merging into the develop branch instead of main

**Comment by fubaru** [comment]
Closing this old one to approve new one

**Pull request closed without merging**
